//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	securityexception "github.com/kubescape/storage/pkg/apis/securityexception"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterSecurityException)(nil), (*securityexception.ClusterSecurityException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterSecurityException_To_securityexception_ClusterSecurityException(a.(*ClusterSecurityException), b.(*securityexception.ClusterSecurityException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.ClusterSecurityException)(nil), (*ClusterSecurityException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_ClusterSecurityException_To_v1_ClusterSecurityException(a.(*securityexception.ClusterSecurityException), b.(*ClusterSecurityException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSecurityExceptionList)(nil), (*securityexception.ClusterSecurityExceptionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterSecurityExceptionList_To_securityexception_ClusterSecurityExceptionList(a.(*ClusterSecurityExceptionList), b.(*securityexception.ClusterSecurityExceptionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.ClusterSecurityExceptionList)(nil), (*ClusterSecurityExceptionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_ClusterSecurityExceptionList_To_v1_ClusterSecurityExceptionList(a.(*securityexception.ClusterSecurityExceptionList), b.(*ClusterSecurityExceptionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExceptionMatch)(nil), (*securityexception.ExceptionMatch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ExceptionMatch_To_securityexception_ExceptionMatch(a.(*ExceptionMatch), b.(*securityexception.ExceptionMatch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.ExceptionMatch)(nil), (*ExceptionMatch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_ExceptionMatch_To_v1_ExceptionMatch(a.(*securityexception.ExceptionMatch), b.(*ExceptionMatch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PostureException)(nil), (*securityexception.PostureException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PostureException_To_securityexception_PostureException(a.(*PostureException), b.(*securityexception.PostureException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.PostureException)(nil), (*PostureException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_PostureException_To_v1_PostureException(a.(*securityexception.PostureException), b.(*PostureException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceMatch)(nil), (*securityexception.ResourceMatch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ResourceMatch_To_securityexception_ResourceMatch(a.(*ResourceMatch), b.(*securityexception.ResourceMatch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.ResourceMatch)(nil), (*ResourceMatch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_ResourceMatch_To_v1_ResourceMatch(a.(*securityexception.ResourceMatch), b.(*ResourceMatch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityException)(nil), (*securityexception.SecurityException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SecurityException_To_securityexception_SecurityException(a.(*SecurityException), b.(*securityexception.SecurityException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.SecurityException)(nil), (*SecurityException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_SecurityException_To_v1_SecurityException(a.(*securityexception.SecurityException), b.(*SecurityException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityExceptionList)(nil), (*securityexception.SecurityExceptionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SecurityExceptionList_To_securityexception_SecurityExceptionList(a.(*SecurityExceptionList), b.(*securityexception.SecurityExceptionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.SecurityExceptionList)(nil), (*SecurityExceptionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_SecurityExceptionList_To_v1_SecurityExceptionList(a.(*securityexception.SecurityExceptionList), b.(*SecurityExceptionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityExceptionSpec)(nil), (*securityexception.SecurityExceptionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SecurityExceptionSpec_To_securityexception_SecurityExceptionSpec(a.(*SecurityExceptionSpec), b.(*securityexception.SecurityExceptionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.SecurityExceptionSpec)(nil), (*SecurityExceptionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_SecurityExceptionSpec_To_v1_SecurityExceptionSpec(a.(*securityexception.SecurityExceptionSpec), b.(*SecurityExceptionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VulnerabilityException)(nil), (*securityexception.VulnerabilityException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VulnerabilityException_To_securityexception_VulnerabilityException(a.(*VulnerabilityException), b.(*securityexception.VulnerabilityException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.VulnerabilityException)(nil), (*VulnerabilityException)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_VulnerabilityException_To_v1_VulnerabilityException(a.(*securityexception.VulnerabilityException), b.(*VulnerabilityException), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VulnerabilityRef)(nil), (*securityexception.VulnerabilityRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VulnerabilityRef_To_securityexception_VulnerabilityRef(a.(*VulnerabilityRef), b.(*securityexception.VulnerabilityRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*securityexception.VulnerabilityRef)(nil), (*VulnerabilityRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_securityexception_VulnerabilityRef_To_v1_VulnerabilityRef(a.(*securityexception.VulnerabilityRef), b.(*VulnerabilityRef), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_ClusterSecurityException_To_securityexception_ClusterSecurityException(in *ClusterSecurityException, out *securityexception.ClusterSecurityException, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_SecurityExceptionSpec_To_securityexception_SecurityExceptionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ClusterSecurityException_To_securityexception_ClusterSecurityException is an autogenerated conversion function.
func Convert_v1_ClusterSecurityException_To_securityexception_ClusterSecurityException(in *ClusterSecurityException, out *securityexception.ClusterSecurityException, s conversion.Scope) error {
	return autoConvert_v1_ClusterSecurityException_To_securityexception_ClusterSecurityException(in, out, s)
}

func autoConvert_securityexception_ClusterSecurityException_To_v1_ClusterSecurityException(in *securityexception.ClusterSecurityException, out *ClusterSecurityException, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_securityexception_SecurityExceptionSpec_To_v1_SecurityExceptionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_securityexception_ClusterSecurityException_To_v1_ClusterSecurityException is an autogenerated conversion function.
func Convert_securityexception_ClusterSecurityException_To_v1_ClusterSecurityException(in *securityexception.ClusterSecurityException, out *ClusterSecurityException, s conversion.Scope) error {
	return autoConvert_securityexception_ClusterSecurityException_To_v1_ClusterSecurityException(in, out, s)
}

func autoConvert_v1_ClusterSecurityExceptionList_To_securityexception_ClusterSecurityExceptionList(in *ClusterSecurityExceptionList, out *securityexception.ClusterSecurityExceptionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]securityexception.ClusterSecurityException)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ClusterSecurityExceptionList_To_securityexception_ClusterSecurityExceptionList is an autogenerated conversion function.
func Convert_v1_ClusterSecurityExceptionList_To_securityexception_ClusterSecurityExceptionList(in *ClusterSecurityExceptionList, out *securityexception.ClusterSecurityExceptionList, s conversion.Scope) error {
	return autoConvert_v1_ClusterSecurityExceptionList_To_securityexception_ClusterSecurityExceptionList(in, out, s)
}

func autoConvert_securityexception_ClusterSecurityExceptionList_To_v1_ClusterSecurityExceptionList(in *securityexception.ClusterSecurityExceptionList, out *ClusterSecurityExceptionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterSecurityException)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_securityexception_ClusterSecurityExceptionList_To_v1_ClusterSecurityExceptionList is an autogenerated conversion function.
func Convert_securityexception_ClusterSecurityExceptionList_To_v1_ClusterSecurityExceptionList(in *securityexception.ClusterSecurityExceptionList, out *ClusterSecurityExceptionList, s conversion.Scope) error {
	return autoConvert_securityexception_ClusterSecurityExceptionList_To_v1_ClusterSecurityExceptionList(in, out, s)
}

func autoConvert_v1_ExceptionMatch_To_securityexception_ExceptionMatch(in *ExceptionMatch, out *securityexception.ExceptionMatch, s conversion.Scope) error {
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.ObjectSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.ObjectSelector))
	out.Resources = *(*[]securityexception.ResourceMatch)(unsafe.Pointer(&in.Resources))
	out.Images = *(*[]string)(unsafe.Pointer(&in.Images))
	return nil
}

// Convert_v1_ExceptionMatch_To_securityexception_ExceptionMatch is an autogenerated conversion function.
func Convert_v1_ExceptionMatch_To_securityexception_ExceptionMatch(in *ExceptionMatch, out *securityexception.ExceptionMatch, s conversion.Scope) error {
	return autoConvert_v1_ExceptionMatch_To_securityexception_ExceptionMatch(in, out, s)
}

func autoConvert_securityexception_ExceptionMatch_To_v1_ExceptionMatch(in *securityexception.ExceptionMatch, out *ExceptionMatch, s conversion.Scope) error {
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.ObjectSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.ObjectSelector))
	out.Resources = *(*[]ResourceMatch)(unsafe.Pointer(&in.Resources))
	out.Images = *(*[]string)(unsafe.Pointer(&in.Images))
	return nil
}

// Convert_securityexception_ExceptionMatch_To_v1_ExceptionMatch is an autogenerated conversion function.
func Convert_securityexception_ExceptionMatch_To_v1_ExceptionMatch(in *securityexception.ExceptionMatch, out *ExceptionMatch, s conversion.Scope) error {
	return autoConvert_securityexception_ExceptionMatch_To_v1_ExceptionMatch(in, out, s)
}

func autoConvert_v1_PostureException_To_securityexception_PostureException(in *PostureException, out *securityexception.PostureException, s conversion.Scope) error {
	out.ControlID = in.ControlID
	out.FrameworkName = in.FrameworkName
	out.Action = in.Action
	return nil
}

// Convert_v1_PostureException_To_securityexception_PostureException is an autogenerated conversion function.
func Convert_v1_PostureException_To_securityexception_PostureException(in *PostureException, out *securityexception.PostureException, s conversion.Scope) error {
	return autoConvert_v1_PostureException_To_securityexception_PostureException(in, out, s)
}

func autoConvert_securityexception_PostureException_To_v1_PostureException(in *securityexception.PostureException, out *PostureException, s conversion.Scope) error {
	out.ControlID = in.ControlID
	out.FrameworkName = in.FrameworkName
	out.Action = in.Action
	return nil
}

// Convert_securityexception_PostureException_To_v1_PostureException is an autogenerated conversion function.
func Convert_securityexception_PostureException_To_v1_PostureException(in *securityexception.PostureException, out *PostureException, s conversion.Scope) error {
	return autoConvert_securityexception_PostureException_To_v1_PostureException(in, out, s)
}

func autoConvert_v1_ResourceMatch_To_securityexception_ResourceMatch(in *ResourceMatch, out *securityexception.ResourceMatch, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_v1_ResourceMatch_To_securityexception_ResourceMatch is an autogenerated conversion function.
func Convert_v1_ResourceMatch_To_securityexception_ResourceMatch(in *ResourceMatch, out *securityexception.ResourceMatch, s conversion.Scope) error {
	return autoConvert_v1_ResourceMatch_To_securityexception_ResourceMatch(in, out, s)
}

func autoConvert_securityexception_ResourceMatch_To_v1_ResourceMatch(in *securityexception.ResourceMatch, out *ResourceMatch, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_securityexception_ResourceMatch_To_v1_ResourceMatch is an autogenerated conversion function.
func Convert_securityexception_ResourceMatch_To_v1_ResourceMatch(in *securityexception.ResourceMatch, out *ResourceMatch, s conversion.Scope) error {
	return autoConvert_securityexception_ResourceMatch_To_v1_ResourceMatch(in, out, s)
}

func autoConvert_v1_SecurityException_To_securityexception_SecurityException(in *SecurityException, out *securityexception.SecurityException, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_SecurityExceptionSpec_To_securityexception_SecurityExceptionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_SecurityException_To_securityexception_SecurityException is an autogenerated conversion function.
func Convert_v1_SecurityException_To_securityexception_SecurityException(in *SecurityException, out *securityexception.SecurityException, s conversion.Scope) error {
	return autoConvert_v1_SecurityException_To_securityexception_SecurityException(in, out, s)
}

func autoConvert_securityexception_SecurityException_To_v1_SecurityException(in *securityexception.SecurityException, out *SecurityException, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_securityexception_SecurityExceptionSpec_To_v1_SecurityExceptionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_securityexception_SecurityException_To_v1_SecurityException is an autogenerated conversion function.
func Convert_securityexception_SecurityException_To_v1_SecurityException(in *securityexception.SecurityException, out *SecurityException, s conversion.Scope) error {
	return autoConvert_securityexception_SecurityException_To_v1_SecurityException(in, out, s)
}

func autoConvert_v1_SecurityExceptionList_To_securityexception_SecurityExceptionList(in *SecurityExceptionList, out *securityexception.SecurityExceptionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]securityexception.SecurityException)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_SecurityExceptionList_To_securityexception_SecurityExceptionList is an autogenerated conversion function.
func Convert_v1_SecurityExceptionList_To_securityexception_SecurityExceptionList(in *SecurityExceptionList, out *securityexception.SecurityExceptionList, s conversion.Scope) error {
	return autoConvert_v1_SecurityExceptionList_To_securityexception_SecurityExceptionList(in, out, s)
}

func autoConvert_securityexception_SecurityExceptionList_To_v1_SecurityExceptionList(in *securityexception.SecurityExceptionList, out *SecurityExceptionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SecurityException)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_securityexception_SecurityExceptionList_To_v1_SecurityExceptionList is an autogenerated conversion function.
func Convert_securityexception_SecurityExceptionList_To_v1_SecurityExceptionList(in *securityexception.SecurityExceptionList, out *SecurityExceptionList, s conversion.Scope) error {
	return autoConvert_securityexception_SecurityExceptionList_To_v1_SecurityExceptionList(in, out, s)
}

func autoConvert_v1_SecurityExceptionSpec_To_securityexception_SecurityExceptionSpec(in *SecurityExceptionSpec, out *securityexception.SecurityExceptionSpec, s conversion.Scope) error {
	out.Author = in.Author
	out.Reason = in.Reason
	out.ExpiresAt = (*metav1.Time)(unsafe.Pointer(in.ExpiresAt))
	if err := Convert_v1_ExceptionMatch_To_securityexception_ExceptionMatch(&in.Match, &out.Match, s); err != nil {
		return err
	}
	out.Vulnerabilities = *(*[]securityexception.VulnerabilityException)(unsafe.Pointer(&in.Vulnerabilities))
	out.Posture = *(*[]securityexception.PostureException)(unsafe.Pointer(&in.Posture))
	return nil
}

// Convert_v1_SecurityExceptionSpec_To_securityexception_SecurityExceptionSpec is an autogenerated conversion function.
func Convert_v1_SecurityExceptionSpec_To_securityexception_SecurityExceptionSpec(in *SecurityExceptionSpec, out *securityexception.SecurityExceptionSpec, s conversion.Scope) error {
	return autoConvert_v1_SecurityExceptionSpec_To_securityexception_SecurityExceptionSpec(in, out, s)
}

func autoConvert_securityexception_SecurityExceptionSpec_To_v1_SecurityExceptionSpec(in *securityexception.SecurityExceptionSpec, out *SecurityExceptionSpec, s conversion.Scope) error {
	out.Author = in.Author
	out.Reason = in.Reason
	out.ExpiresAt = (*metav1.Time)(unsafe.Pointer(in.ExpiresAt))
	if err := Convert_securityexception_ExceptionMatch_To_v1_ExceptionMatch(&in.Match, &out.Match, s); err != nil {
		return err
	}
	out.Vulnerabilities = *(*[]VulnerabilityException)(unsafe.Pointer(&in.Vulnerabilities))
	out.Posture = *(*[]PostureException)(unsafe.Pointer(&in.Posture))
	return nil
}

// Convert_securityexception_SecurityExceptionSpec_To_v1_SecurityExceptionSpec is an autogenerated conversion function.
func Convert_securityexception_SecurityExceptionSpec_To_v1_SecurityExceptionSpec(in *securityexception.SecurityExceptionSpec, out *SecurityExceptionSpec, s conversion.Scope) error {
	return autoConvert_securityexception_SecurityExceptionSpec_To_v1_SecurityExceptionSpec(in, out, s)
}

func autoConvert_v1_VulnerabilityException_To_securityexception_VulnerabilityException(in *VulnerabilityException, out *securityexception.VulnerabilityException, s conversion.Scope) error {
	if err := Convert_v1_VulnerabilityRef_To_securityexception_VulnerabilityRef(&in.Vulnerability, &out.Vulnerability, s); err != nil {
		return err
	}
	out.Status = in.Status
	out.Justification = in.Justification
	out.ImpactStatement = in.ImpactStatement
	out.ExpiredOnFix = in.ExpiredOnFix
	return nil
}

// Convert_v1_VulnerabilityException_To_securityexception_VulnerabilityException is an autogenerated conversion function.
func Convert_v1_VulnerabilityException_To_securityexception_VulnerabilityException(in *VulnerabilityException, out *securityexception.VulnerabilityException, s conversion.Scope) error {
	return autoConvert_v1_VulnerabilityException_To_securityexception_VulnerabilityException(in, out, s)
}

func autoConvert_securityexception_VulnerabilityException_To_v1_VulnerabilityException(in *securityexception.VulnerabilityException, out *VulnerabilityException, s conversion.Scope) error {
	if err := Convert_securityexception_VulnerabilityRef_To_v1_VulnerabilityRef(&in.Vulnerability, &out.Vulnerability, s); err != nil {
		return err
	}
	out.Status = in.Status
	out.Justification = in.Justification
	out.ImpactStatement = in.ImpactStatement
	out.ExpiredOnFix = in.ExpiredOnFix
	return nil
}

// Convert_securityexception_VulnerabilityException_To_v1_VulnerabilityException is an autogenerated conversion function.
func Convert_securityexception_VulnerabilityException_To_v1_VulnerabilityException(in *securityexception.VulnerabilityException, out *VulnerabilityException, s conversion.Scope) error {
	return autoConvert_securityexception_VulnerabilityException_To_v1_VulnerabilityException(in, out, s)
}

func autoConvert_v1_VulnerabilityRef_To_securityexception_VulnerabilityRef(in *VulnerabilityRef, out *securityexception.VulnerabilityRef, s conversion.Scope) error {
	out.ID = in.ID
	out.Aliases = *(*[]string)(unsafe.Pointer(&in.Aliases))
	return nil
}

// Convert_v1_VulnerabilityRef_To_securityexception_VulnerabilityRef is an autogenerated conversion function.
func Convert_v1_VulnerabilityRef_To_securityexception_VulnerabilityRef(in *VulnerabilityRef, out *securityexception.VulnerabilityRef, s conversion.Scope) error {
	return autoConvert_v1_VulnerabilityRef_To_securityexception_VulnerabilityRef(in, out, s)
}

func autoConvert_securityexception_VulnerabilityRef_To_v1_VulnerabilityRef(in *securityexception.VulnerabilityRef, out *VulnerabilityRef, s conversion.Scope) error {
	out.ID = in.ID
	out.Aliases = *(*[]string)(unsafe.Pointer(&in.Aliases))
	return nil
}

// Convert_securityexception_VulnerabilityRef_To_v1_VulnerabilityRef is an autogenerated conversion function.
func Convert_securityexception_VulnerabilityRef_To_v1_VulnerabilityRef(in *securityexception.VulnerabilityRef, out *VulnerabilityRef, s conversion.Scope) error {
	return autoConvert_securityexception_VulnerabilityRef_To_v1_VulnerabilityRef(in, out, s)
}
