//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by go-to-protobuf. DO NOT EDIT.

package v1beta1

func (*Advisory) ProtoMessage() {}

func (*ApplicationProfile) ProtoMessage() {}

func (*ApplicationProfileContainer) ProtoMessage() {}

func (*ApplicationProfileList) ProtoMessage() {}

func (*ApplicationProfileSpec) ProtoMessage() {}

func (*ApplicationProfileStatus) ProtoMessage() {}

func (*Arg) ProtoMessage() {}

func (*CPE) ProtoMessage() {}

func (*CallStack) ProtoMessage() {}

func (*CallStackNode) ProtoMessage() {}

func (*Component) ProtoMessage() {}

func (*Condition) ProtoMessage() {}

func (*ConditionedStatus) ProtoMessage() {}

func (*ConfigurationScanSummary) ProtoMessage() {}

func (*ConfigurationScanSummaryList) ProtoMessage() {}

func (*ConfigurationScanSummarySpec) ProtoMessage() {}

func (*ContainerProfile) ProtoMessage() {}

func (*ContainerProfileList) ProtoMessage() {}

func (*ContainerProfileSpec) ProtoMessage() {}

func (*ContainerProfileStatus) ProtoMessage() {}

func (*ControlSeverity) ProtoMessage() {}

func (*Coordinates) ProtoMessage() {}

func (*Cvss) ProtoMessage() {}

func (*CvssMetrics) ProtoMessage() {}

func (*Descriptor) ProtoMessage() {}

func (*Digest) ProtoMessage() {}

func (*Distribution) ProtoMessage() {}

func (*ELFSecurityFeatures) ProtoMessage() {}

func (*ExecCalls) ProtoMessage() {}

func (*Executable) ProtoMessage() {}

func (*FileLicense) ProtoMessage() {}

func (*FileLicenseEvidence) ProtoMessage() {}

func (*FileMetadataEntry) ProtoMessage() {}

func (*Fix) ProtoMessage() {}

func (*GeneratedNetworkPolicy) ProtoMessage() {}

func (*GeneratedNetworkPolicyList) ProtoMessage() {}

func (*GrypeDocument) ProtoMessage() {}

func (*GrypePackage) ProtoMessage() {}

func (*HTTPEndpoint) ProtoMessage() {}

func (*HTTPIngressPath) ProtoMessage() {}

func (*HTTPIngressRuleValue) ProtoMessage() {}

func (*IPBlock) ProtoMessage() {}

func (*IdentifiedCallStack) ProtoMessage() {}

func (*IgnoreRule) ProtoMessage() {}

func (*IgnoreRulePackage) ProtoMessage() {}

func (*IgnoredMatch) ProtoMessage() {}

func (*Ingress) ProtoMessage() {}

func (*IngressBackend) ProtoMessage() {}

func (*IngressClass) ProtoMessage() {}

func (*IngressClassList) ProtoMessage() {}

func (*IngressClassParametersReference) ProtoMessage() {}

func (*IngressClassSpec) ProtoMessage() {}

func (*IngressList) ProtoMessage() {}

func (*IngressLoadBalancerIngress) ProtoMessage() {}

func (*IngressLoadBalancerStatus) ProtoMessage() {}

func (*IngressPortStatus) ProtoMessage() {}

func (*IngressRule) ProtoMessage() {}

func (*IngressRuleValue) ProtoMessage() {}

func (*IngressServiceBackend) ProtoMessage() {}

func (*IngressSpec) ProtoMessage() {}

func (*IngressStatus) ProtoMessage() {}

func (*IngressTLS) ProtoMessage() {}

func (*KnownServer) ProtoMessage() {}

func (*KnownServerEntry) ProtoMessage() {}

func (*KnownServerList) ProtoMessage() {}

func (*License) ProtoMessage() {}

func (*LinuxRelease) ProtoMessage() {}

func (*Location) ProtoMessage() {}

func (*LocationData) ProtoMessage() {}

func (*LocationMetadata) ProtoMessage() {}

func (*Match) ProtoMessage() {}

func (*MatchDetails) ProtoMessage() {}

func (*Metadata) ProtoMessage() {}

func (*NetworkNeighbor) ProtoMessage() {}

func (*NetworkNeighborhood) ProtoMessage() {}

func (*NetworkNeighborhoodContainer) ProtoMessage() {}

func (*NetworkNeighborhoodList) ProtoMessage() {}

func (*NetworkNeighborhoodSpec) ProtoMessage() {}

func (*NetworkPolicy) ProtoMessage() {}

func (*NetworkPolicyEgressRule) ProtoMessage() {}

func (*NetworkPolicyIngressRule) ProtoMessage() {}

func (*NetworkPolicyList) ProtoMessage() {}

func (*NetworkPolicyPeer) ProtoMessage() {}

func (*NetworkPolicyPort) ProtoMessage() {}

func (*NetworkPolicySpec) ProtoMessage() {}

func (*NetworkPolicyStatus) ProtoMessage() {}

func (*NetworkPort) ProtoMessage() {}

func (*OpenCalls) ProtoMessage() {}

func (*OpenVulnerabilityExchangeContainer) ProtoMessage() {}

func (*OpenVulnerabilityExchangeContainerList) ProtoMessage() {}

func (*PackageBasicData) ProtoMessage() {}

func (*PackageBasicDataV01011) ProtoMessage() {}

func (*PackageCustomData) ProtoMessage() {}

func (*PolicyRef) ProtoMessage() {}

func (*Product) ProtoMessage() {}

func (*ReportMeta) ProtoMessage() {}

func (*RulePath) ProtoMessage() {}

func (*RulePolicy) ProtoMessage() {}

func (*RuleStatus) ProtoMessage() {}

func (*SBOMSyft) ProtoMessage() {}

func (*SBOMSyftFiltered) ProtoMessage() {}

func (*SBOMSyftFilteredList) ProtoMessage() {}

func (*SBOMSyftList) ProtoMessage() {}

func (*SBOMSyftSpec) ProtoMessage() {}

func (*SBOMSyftStatus) ProtoMessage() {}

func (*SPDXMeta) ProtoMessage() {}

func (*ScannedControl) ProtoMessage() {}

func (*ScannedControlRule) ProtoMessage() {}

func (*ScannedControlStatus) ProtoMessage() {}

func (*ScannedControlSummary) ProtoMessage() {}

func (*Schema) ProtoMessage() {}

func (*SeccompProfile) ProtoMessage() {}

func (*SeccompProfileList) ProtoMessage() {}

func (*SeccompProfileSpec) ProtoMessage() {}

func (*SeccompProfileStatus) ProtoMessage() {}

func (*ServiceBackendPort) ProtoMessage() {}

func (*SeveritySummary) ProtoMessage() {}

func (*SingleSeccompProfile) ProtoMessage() {}

func (*SingleSeccompProfileSpec) ProtoMessage() {}

func (*SingleSeccompProfileStatus) ProtoMessage() {}

func (*Source) ProtoMessage() {}

func (*SpecBase) ProtoMessage() {}

func (*StackFrame) ProtoMessage() {}

func (*Statement) ProtoMessage() {}

func (*StatusBase) ProtoMessage() {}

func (*Subcomponent) ProtoMessage() {}

func (*SyftCoordinates) ProtoMessage() {}

func (*SyftDescriptor) ProtoMessage() {}

func (*SyftDocument) ProtoMessage() {}

func (*SyftFile) ProtoMessage() {}

func (*SyftPackage) ProtoMessage() {}

func (*SyftRelationship) ProtoMessage() {}

func (*SyftSource) ProtoMessage() {}

func (*Syscall) ProtoMessage() {}

func (*ToolMeta) ProtoMessage() {}

func (*UpstreamPackage) ProtoMessage() {}

func (*VEX) ProtoMessage() {}

func (*VexVulnerability) ProtoMessage() {}

func (*VulnerabilitiesComponents) ProtoMessage() {}

func (*VulnerabilitiesObjScope) ProtoMessage() {}

func (*Vulnerability) ProtoMessage() {}

func (*VulnerabilityCounters) ProtoMessage() {}

func (*VulnerabilityManifest) ProtoMessage() {}

func (*VulnerabilityManifestList) ProtoMessage() {}

func (*VulnerabilityManifestMeta) ProtoMessage() {}

func (*VulnerabilityManifestReportMeta) ProtoMessage() {}

func (*VulnerabilityManifestSpec) ProtoMessage() {}

func (*VulnerabilityManifestStatus) ProtoMessage() {}

func (*VulnerabilityManifestSummary) ProtoMessage() {}

func (*VulnerabilityManifestSummaryList) ProtoMessage() {}

func (*VulnerabilityManifestSummarySpec) ProtoMessage() {}

func (*VulnerabilityManifestToolMeta) ProtoMessage() {}

func (*VulnerabilityMetadata) ProtoMessage() {}

func (*VulnerabilitySummary) ProtoMessage() {}

func (*VulnerabilitySummaryList) ProtoMessage() {}

func (*VulnerabilitySummarySpec) ProtoMessage() {}

func (*VulnerabilitySummaryStatus) ProtoMessage() {}

func (*WorkloadConfigurationScan) ProtoMessage() {}

func (*WorkloadConfigurationScanList) ProtoMessage() {}

func (*WorkloadConfigurationScanSeveritiesSummary) ProtoMessage() {}

func (*WorkloadConfigurationScanSpec) ProtoMessage() {}

func (*WorkloadConfigurationScanSummary) ProtoMessage() {}

func (*WorkloadConfigurationScanSummaryIdentifier) ProtoMessage() {}

func (*WorkloadConfigurationScanSummaryList) ProtoMessage() {}

func (*WorkloadConfigurationScanSummarySpec) ProtoMessage() {}

func (*WorkloadScanRelatedObject) ProtoMessage() {}
