//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	softwarecomposition "k8s.io/sample-apiserver/pkg/apis/softwarecomposition"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Annotation)(nil), (*softwarecomposition.Annotation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Annotation_To_softwarecomposition_Annotation(a.(*Annotation), b.(*softwarecomposition.Annotation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Annotation)(nil), (*Annotation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Annotation_To_v1beta1_Annotation(a.(*softwarecomposition.Annotation), b.(*Annotation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Annotator)(nil), (*softwarecomposition.Annotator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Annotator_To_softwarecomposition_Annotator(a.(*Annotator), b.(*softwarecomposition.Annotator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Annotator)(nil), (*Annotator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Annotator_To_v1beta1_Annotator(a.(*softwarecomposition.Annotator), b.(*Annotator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactOfProject)(nil), (*softwarecomposition.ArtifactOfProject)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ArtifactOfProject_To_softwarecomposition_ArtifactOfProject(a.(*ArtifactOfProject), b.(*softwarecomposition.ArtifactOfProject), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.ArtifactOfProject)(nil), (*ArtifactOfProject)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_ArtifactOfProject_To_v1beta1_ArtifactOfProject(a.(*softwarecomposition.ArtifactOfProject), b.(*ArtifactOfProject), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Checksum)(nil), (*softwarecomposition.Checksum)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Checksum_To_softwarecomposition_Checksum(a.(*Checksum), b.(*softwarecomposition.Checksum), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Checksum)(nil), (*Checksum)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Checksum_To_v1beta1_Checksum(a.(*softwarecomposition.Checksum), b.(*Checksum), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CreationInfo)(nil), (*softwarecomposition.CreationInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CreationInfo_To_softwarecomposition_CreationInfo(a.(*CreationInfo), b.(*softwarecomposition.CreationInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.CreationInfo)(nil), (*CreationInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_CreationInfo_To_v1beta1_CreationInfo(a.(*softwarecomposition.CreationInfo), b.(*CreationInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Creator)(nil), (*softwarecomposition.Creator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Creator_To_softwarecomposition_Creator(a.(*Creator), b.(*softwarecomposition.Creator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Creator)(nil), (*Creator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Creator_To_v1beta1_Creator(a.(*softwarecomposition.Creator), b.(*Creator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DocElementID)(nil), (*softwarecomposition.DocElementID)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DocElementID_To_softwarecomposition_DocElementID(a.(*DocElementID), b.(*softwarecomposition.DocElementID), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.DocElementID)(nil), (*DocElementID)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_DocElementID_To_v1beta1_DocElementID(a.(*softwarecomposition.DocElementID), b.(*DocElementID), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Document)(nil), (*softwarecomposition.Document)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Document_To_softwarecomposition_Document(a.(*Document), b.(*softwarecomposition.Document), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Document)(nil), (*Document)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Document_To_v1beta1_Document(a.(*softwarecomposition.Document), b.(*Document), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalDocumentRef)(nil), (*softwarecomposition.ExternalDocumentRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ExternalDocumentRef_To_softwarecomposition_ExternalDocumentRef(a.(*ExternalDocumentRef), b.(*softwarecomposition.ExternalDocumentRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.ExternalDocumentRef)(nil), (*ExternalDocumentRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_ExternalDocumentRef_To_v1beta1_ExternalDocumentRef(a.(*softwarecomposition.ExternalDocumentRef), b.(*ExternalDocumentRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*softwarecomposition.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_File_To_softwarecomposition_File(a.(*File), b.(*softwarecomposition.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_File_To_v1beta1_File(a.(*softwarecomposition.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Originator)(nil), (*softwarecomposition.Originator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Originator_To_softwarecomposition_Originator(a.(*Originator), b.(*softwarecomposition.Originator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Originator)(nil), (*Originator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Originator_To_v1beta1_Originator(a.(*softwarecomposition.Originator), b.(*Originator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OtherLicense)(nil), (*softwarecomposition.OtherLicense)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OtherLicense_To_softwarecomposition_OtherLicense(a.(*OtherLicense), b.(*softwarecomposition.OtherLicense), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.OtherLicense)(nil), (*OtherLicense)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_OtherLicense_To_v1beta1_OtherLicense(a.(*softwarecomposition.OtherLicense), b.(*OtherLicense), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Package)(nil), (*softwarecomposition.Package)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Package_To_softwarecomposition_Package(a.(*Package), b.(*softwarecomposition.Package), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Package)(nil), (*Package)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Package_To_v1beta1_Package(a.(*softwarecomposition.Package), b.(*Package), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageExternalReference)(nil), (*softwarecomposition.PackageExternalReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PackageExternalReference_To_softwarecomposition_PackageExternalReference(a.(*PackageExternalReference), b.(*softwarecomposition.PackageExternalReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.PackageExternalReference)(nil), (*PackageExternalReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_PackageExternalReference_To_v1beta1_PackageExternalReference(a.(*softwarecomposition.PackageExternalReference), b.(*PackageExternalReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageVerificationCode)(nil), (*softwarecomposition.PackageVerificationCode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PackageVerificationCode_To_softwarecomposition_PackageVerificationCode(a.(*PackageVerificationCode), b.(*softwarecomposition.PackageVerificationCode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.PackageVerificationCode)(nil), (*PackageVerificationCode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_PackageVerificationCode_To_v1beta1_PackageVerificationCode(a.(*softwarecomposition.PackageVerificationCode), b.(*PackageVerificationCode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Relationship)(nil), (*softwarecomposition.Relationship)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Relationship_To_softwarecomposition_Relationship(a.(*Relationship), b.(*softwarecomposition.Relationship), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Relationship)(nil), (*Relationship)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Relationship_To_v1beta1_Relationship(a.(*softwarecomposition.Relationship), b.(*Relationship), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Review)(nil), (*softwarecomposition.Review)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Review_To_softwarecomposition_Review(a.(*Review), b.(*softwarecomposition.Review), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Review)(nil), (*Review)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Review_To_v1beta1_Review(a.(*softwarecomposition.Review), b.(*Review), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SBOMSPDXv2p3)(nil), (*softwarecomposition.SBOMSPDXv2p3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SBOMSPDXv2p3_To_softwarecomposition_SBOMSPDXv2p3(a.(*SBOMSPDXv2p3), b.(*softwarecomposition.SBOMSPDXv2p3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.SBOMSPDXv2p3)(nil), (*SBOMSPDXv2p3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_SBOMSPDXv2p3_To_v1beta1_SBOMSPDXv2p3(a.(*softwarecomposition.SBOMSPDXv2p3), b.(*SBOMSPDXv2p3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SBOMSPDXv2p3List)(nil), (*softwarecomposition.SBOMSPDXv2p3List)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SBOMSPDXv2p3List_To_softwarecomposition_SBOMSPDXv2p3List(a.(*SBOMSPDXv2p3List), b.(*softwarecomposition.SBOMSPDXv2p3List), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.SBOMSPDXv2p3List)(nil), (*SBOMSPDXv2p3List)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_SBOMSPDXv2p3List_To_v1beta1_SBOMSPDXv2p3List(a.(*softwarecomposition.SBOMSPDXv2p3List), b.(*SBOMSPDXv2p3List), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SBOMSPDXv2p3Spec)(nil), (*softwarecomposition.SBOMSPDXv2p3Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SBOMSPDXv2p3Spec_To_softwarecomposition_SBOMSPDXv2p3Spec(a.(*SBOMSPDXv2p3Spec), b.(*softwarecomposition.SBOMSPDXv2p3Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.SBOMSPDXv2p3Spec)(nil), (*SBOMSPDXv2p3Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_SBOMSPDXv2p3Spec_To_v1beta1_SBOMSPDXv2p3Spec(a.(*softwarecomposition.SBOMSPDXv2p3Spec), b.(*SBOMSPDXv2p3Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SBOMSPDXv2p3Status)(nil), (*softwarecomposition.SBOMSPDXv2p3Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SBOMSPDXv2p3Status_To_softwarecomposition_SBOMSPDXv2p3Status(a.(*SBOMSPDXv2p3Status), b.(*softwarecomposition.SBOMSPDXv2p3Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.SBOMSPDXv2p3Status)(nil), (*SBOMSPDXv2p3Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_SBOMSPDXv2p3Status_To_v1beta1_SBOMSPDXv2p3Status(a.(*softwarecomposition.SBOMSPDXv2p3Status), b.(*SBOMSPDXv2p3Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Snippet)(nil), (*softwarecomposition.Snippet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Snippet_To_softwarecomposition_Snippet(a.(*Snippet), b.(*softwarecomposition.Snippet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Snippet)(nil), (*Snippet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Snippet_To_v1beta1_Snippet(a.(*softwarecomposition.Snippet), b.(*Snippet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnippetRange)(nil), (*softwarecomposition.SnippetRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnippetRange_To_softwarecomposition_SnippetRange(a.(*SnippetRange), b.(*softwarecomposition.SnippetRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.SnippetRange)(nil), (*SnippetRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_SnippetRange_To_v1beta1_SnippetRange(a.(*softwarecomposition.SnippetRange), b.(*SnippetRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnippetRangePointer)(nil), (*softwarecomposition.SnippetRangePointer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnippetRangePointer_To_softwarecomposition_SnippetRangePointer(a.(*SnippetRangePointer), b.(*softwarecomposition.SnippetRangePointer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.SnippetRangePointer)(nil), (*SnippetRangePointer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_SnippetRangePointer_To_v1beta1_SnippetRangePointer(a.(*softwarecomposition.SnippetRangePointer), b.(*SnippetRangePointer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Supplier)(nil), (*softwarecomposition.Supplier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Supplier_To_softwarecomposition_Supplier(a.(*Supplier), b.(*softwarecomposition.Supplier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*softwarecomposition.Supplier)(nil), (*Supplier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_softwarecomposition_Supplier_To_v1beta1_Supplier(a.(*softwarecomposition.Supplier), b.(*Supplier), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Annotation_To_softwarecomposition_Annotation(in *Annotation, out *softwarecomposition.Annotation, s conversion.Scope) error {
	if err := Convert_v1beta1_Annotator_To_softwarecomposition_Annotator(&in.Annotator, &out.Annotator, s); err != nil {
		return err
	}
	out.AnnotationDate = in.AnnotationDate
	out.AnnotationType = in.AnnotationType
	if err := Convert_v1beta1_DocElementID_To_softwarecomposition_DocElementID(&in.AnnotationSPDXIdentifier, &out.AnnotationSPDXIdentifier, s); err != nil {
		return err
	}
	out.AnnotationComment = in.AnnotationComment
	return nil
}

// Convert_v1beta1_Annotation_To_softwarecomposition_Annotation is an autogenerated conversion function.
func Convert_v1beta1_Annotation_To_softwarecomposition_Annotation(in *Annotation, out *softwarecomposition.Annotation, s conversion.Scope) error {
	return autoConvert_v1beta1_Annotation_To_softwarecomposition_Annotation(in, out, s)
}

func autoConvert_softwarecomposition_Annotation_To_v1beta1_Annotation(in *softwarecomposition.Annotation, out *Annotation, s conversion.Scope) error {
	if err := Convert_softwarecomposition_Annotator_To_v1beta1_Annotator(&in.Annotator, &out.Annotator, s); err != nil {
		return err
	}
	out.AnnotationDate = in.AnnotationDate
	out.AnnotationType = in.AnnotationType
	if err := Convert_softwarecomposition_DocElementID_To_v1beta1_DocElementID(&in.AnnotationSPDXIdentifier, &out.AnnotationSPDXIdentifier, s); err != nil {
		return err
	}
	out.AnnotationComment = in.AnnotationComment
	return nil
}

// Convert_softwarecomposition_Annotation_To_v1beta1_Annotation is an autogenerated conversion function.
func Convert_softwarecomposition_Annotation_To_v1beta1_Annotation(in *softwarecomposition.Annotation, out *Annotation, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Annotation_To_v1beta1_Annotation(in, out, s)
}

func autoConvert_v1beta1_Annotator_To_softwarecomposition_Annotator(in *Annotator, out *softwarecomposition.Annotator, s conversion.Scope) error {
	out.Annotator = in.Annotator
	out.AnnotatorType = in.AnnotatorType
	return nil
}

// Convert_v1beta1_Annotator_To_softwarecomposition_Annotator is an autogenerated conversion function.
func Convert_v1beta1_Annotator_To_softwarecomposition_Annotator(in *Annotator, out *softwarecomposition.Annotator, s conversion.Scope) error {
	return autoConvert_v1beta1_Annotator_To_softwarecomposition_Annotator(in, out, s)
}

func autoConvert_softwarecomposition_Annotator_To_v1beta1_Annotator(in *softwarecomposition.Annotator, out *Annotator, s conversion.Scope) error {
	out.Annotator = in.Annotator
	out.AnnotatorType = in.AnnotatorType
	return nil
}

// Convert_softwarecomposition_Annotator_To_v1beta1_Annotator is an autogenerated conversion function.
func Convert_softwarecomposition_Annotator_To_v1beta1_Annotator(in *softwarecomposition.Annotator, out *Annotator, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Annotator_To_v1beta1_Annotator(in, out, s)
}

func autoConvert_v1beta1_ArtifactOfProject_To_softwarecomposition_ArtifactOfProject(in *ArtifactOfProject, out *softwarecomposition.ArtifactOfProject, s conversion.Scope) error {
	out.Name = in.Name
	out.HomePage = in.HomePage
	out.URI = in.URI
	return nil
}

// Convert_v1beta1_ArtifactOfProject_To_softwarecomposition_ArtifactOfProject is an autogenerated conversion function.
func Convert_v1beta1_ArtifactOfProject_To_softwarecomposition_ArtifactOfProject(in *ArtifactOfProject, out *softwarecomposition.ArtifactOfProject, s conversion.Scope) error {
	return autoConvert_v1beta1_ArtifactOfProject_To_softwarecomposition_ArtifactOfProject(in, out, s)
}

func autoConvert_softwarecomposition_ArtifactOfProject_To_v1beta1_ArtifactOfProject(in *softwarecomposition.ArtifactOfProject, out *ArtifactOfProject, s conversion.Scope) error {
	out.Name = in.Name
	out.HomePage = in.HomePage
	out.URI = in.URI
	return nil
}

// Convert_softwarecomposition_ArtifactOfProject_To_v1beta1_ArtifactOfProject is an autogenerated conversion function.
func Convert_softwarecomposition_ArtifactOfProject_To_v1beta1_ArtifactOfProject(in *softwarecomposition.ArtifactOfProject, out *ArtifactOfProject, s conversion.Scope) error {
	return autoConvert_softwarecomposition_ArtifactOfProject_To_v1beta1_ArtifactOfProject(in, out, s)
}

func autoConvert_v1beta1_Checksum_To_softwarecomposition_Checksum(in *Checksum, out *softwarecomposition.Checksum, s conversion.Scope) error {
	out.Algorithm = softwarecomposition.ChecksumAlgorithm(in.Algorithm)
	out.Value = in.Value
	return nil
}

// Convert_v1beta1_Checksum_To_softwarecomposition_Checksum is an autogenerated conversion function.
func Convert_v1beta1_Checksum_To_softwarecomposition_Checksum(in *Checksum, out *softwarecomposition.Checksum, s conversion.Scope) error {
	return autoConvert_v1beta1_Checksum_To_softwarecomposition_Checksum(in, out, s)
}

func autoConvert_softwarecomposition_Checksum_To_v1beta1_Checksum(in *softwarecomposition.Checksum, out *Checksum, s conversion.Scope) error {
	out.Algorithm = ChecksumAlgorithm(in.Algorithm)
	out.Value = in.Value
	return nil
}

// Convert_softwarecomposition_Checksum_To_v1beta1_Checksum is an autogenerated conversion function.
func Convert_softwarecomposition_Checksum_To_v1beta1_Checksum(in *softwarecomposition.Checksum, out *Checksum, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Checksum_To_v1beta1_Checksum(in, out, s)
}

func autoConvert_v1beta1_CreationInfo_To_softwarecomposition_CreationInfo(in *CreationInfo, out *softwarecomposition.CreationInfo, s conversion.Scope) error {
	out.LicenseListVersion = in.LicenseListVersion
	out.Creators = *(*[]softwarecomposition.Creator)(unsafe.Pointer(&in.Creators))
	out.Created = in.Created
	out.CreatorComment = in.CreatorComment
	return nil
}

// Convert_v1beta1_CreationInfo_To_softwarecomposition_CreationInfo is an autogenerated conversion function.
func Convert_v1beta1_CreationInfo_To_softwarecomposition_CreationInfo(in *CreationInfo, out *softwarecomposition.CreationInfo, s conversion.Scope) error {
	return autoConvert_v1beta1_CreationInfo_To_softwarecomposition_CreationInfo(in, out, s)
}

func autoConvert_softwarecomposition_CreationInfo_To_v1beta1_CreationInfo(in *softwarecomposition.CreationInfo, out *CreationInfo, s conversion.Scope) error {
	out.LicenseListVersion = in.LicenseListVersion
	out.Creators = *(*[]Creator)(unsafe.Pointer(&in.Creators))
	out.Created = in.Created
	out.CreatorComment = in.CreatorComment
	return nil
}

// Convert_softwarecomposition_CreationInfo_To_v1beta1_CreationInfo is an autogenerated conversion function.
func Convert_softwarecomposition_CreationInfo_To_v1beta1_CreationInfo(in *softwarecomposition.CreationInfo, out *CreationInfo, s conversion.Scope) error {
	return autoConvert_softwarecomposition_CreationInfo_To_v1beta1_CreationInfo(in, out, s)
}

func autoConvert_v1beta1_Creator_To_softwarecomposition_Creator(in *Creator, out *softwarecomposition.Creator, s conversion.Scope) error {
	out.Creator = in.Creator
	out.CreatorType = in.CreatorType
	return nil
}

// Convert_v1beta1_Creator_To_softwarecomposition_Creator is an autogenerated conversion function.
func Convert_v1beta1_Creator_To_softwarecomposition_Creator(in *Creator, out *softwarecomposition.Creator, s conversion.Scope) error {
	return autoConvert_v1beta1_Creator_To_softwarecomposition_Creator(in, out, s)
}

func autoConvert_softwarecomposition_Creator_To_v1beta1_Creator(in *softwarecomposition.Creator, out *Creator, s conversion.Scope) error {
	out.Creator = in.Creator
	out.CreatorType = in.CreatorType
	return nil
}

// Convert_softwarecomposition_Creator_To_v1beta1_Creator is an autogenerated conversion function.
func Convert_softwarecomposition_Creator_To_v1beta1_Creator(in *softwarecomposition.Creator, out *Creator, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Creator_To_v1beta1_Creator(in, out, s)
}

func autoConvert_v1beta1_DocElementID_To_softwarecomposition_DocElementID(in *DocElementID, out *softwarecomposition.DocElementID, s conversion.Scope) error {
	out.DocumentRefID = in.DocumentRefID
	out.ElementRefID = softwarecomposition.ElementID(in.ElementRefID)
	out.SpecialID = in.SpecialID
	return nil
}

// Convert_v1beta1_DocElementID_To_softwarecomposition_DocElementID is an autogenerated conversion function.
func Convert_v1beta1_DocElementID_To_softwarecomposition_DocElementID(in *DocElementID, out *softwarecomposition.DocElementID, s conversion.Scope) error {
	return autoConvert_v1beta1_DocElementID_To_softwarecomposition_DocElementID(in, out, s)
}

func autoConvert_softwarecomposition_DocElementID_To_v1beta1_DocElementID(in *softwarecomposition.DocElementID, out *DocElementID, s conversion.Scope) error {
	out.DocumentRefID = in.DocumentRefID
	out.ElementRefID = ElementID(in.ElementRefID)
	out.SpecialID = in.SpecialID
	return nil
}

// Convert_softwarecomposition_DocElementID_To_v1beta1_DocElementID is an autogenerated conversion function.
func Convert_softwarecomposition_DocElementID_To_v1beta1_DocElementID(in *softwarecomposition.DocElementID, out *DocElementID, s conversion.Scope) error {
	return autoConvert_softwarecomposition_DocElementID_To_v1beta1_DocElementID(in, out, s)
}

func autoConvert_v1beta1_Document_To_softwarecomposition_Document(in *Document, out *softwarecomposition.Document, s conversion.Scope) error {
	out.DocumentDescribes = *(*[]string)(unsafe.Pointer(&in.DocumentDescribes))
	out.SPDXVersion = in.SPDXVersion
	out.DataLicense = in.DataLicense
	out.SPDXIdentifier = softwarecomposition.ElementID(in.SPDXIdentifier)
	out.DocumentName = in.DocumentName
	out.DocumentNamespace = in.DocumentNamespace
	out.ExternalDocumentReferences = *(*[]softwarecomposition.ExternalDocumentRef)(unsafe.Pointer(&in.ExternalDocumentReferences))
	out.DocumentComment = in.DocumentComment
	out.CreationInfo = (*softwarecomposition.CreationInfo)(unsafe.Pointer(in.CreationInfo))
	out.Packages = *(*[]*softwarecomposition.Package)(unsafe.Pointer(&in.Packages))
	out.Files = *(*[]*softwarecomposition.File)(unsafe.Pointer(&in.Files))
	out.OtherLicenses = *(*[]*softwarecomposition.OtherLicense)(unsafe.Pointer(&in.OtherLicenses))
	out.Relationships = *(*[]*softwarecomposition.Relationship)(unsafe.Pointer(&in.Relationships))
	out.Annotations = *(*[]softwarecomposition.Annotation)(unsafe.Pointer(&in.Annotations))
	out.Snippets = *(*[]softwarecomposition.Snippet)(unsafe.Pointer(&in.Snippets))
	out.Reviews = *(*[]*softwarecomposition.Review)(unsafe.Pointer(&in.Reviews))
	return nil
}

// Convert_v1beta1_Document_To_softwarecomposition_Document is an autogenerated conversion function.
func Convert_v1beta1_Document_To_softwarecomposition_Document(in *Document, out *softwarecomposition.Document, s conversion.Scope) error {
	return autoConvert_v1beta1_Document_To_softwarecomposition_Document(in, out, s)
}

func autoConvert_softwarecomposition_Document_To_v1beta1_Document(in *softwarecomposition.Document, out *Document, s conversion.Scope) error {
	out.DocumentDescribes = *(*[]string)(unsafe.Pointer(&in.DocumentDescribes))
	out.SPDXVersion = in.SPDXVersion
	out.DataLicense = in.DataLicense
	out.SPDXIdentifier = ElementID(in.SPDXIdentifier)
	out.DocumentName = in.DocumentName
	out.DocumentNamespace = in.DocumentNamespace
	out.ExternalDocumentReferences = *(*[]ExternalDocumentRef)(unsafe.Pointer(&in.ExternalDocumentReferences))
	out.DocumentComment = in.DocumentComment
	out.CreationInfo = (*CreationInfo)(unsafe.Pointer(in.CreationInfo))
	out.Packages = *(*[]*Package)(unsafe.Pointer(&in.Packages))
	out.Files = *(*[]*File)(unsafe.Pointer(&in.Files))
	out.OtherLicenses = *(*[]*OtherLicense)(unsafe.Pointer(&in.OtherLicenses))
	out.Relationships = *(*[]*Relationship)(unsafe.Pointer(&in.Relationships))
	out.Annotations = *(*[]Annotation)(unsafe.Pointer(&in.Annotations))
	out.Snippets = *(*[]Snippet)(unsafe.Pointer(&in.Snippets))
	out.Reviews = *(*[]*Review)(unsafe.Pointer(&in.Reviews))
	return nil
}

// Convert_softwarecomposition_Document_To_v1beta1_Document is an autogenerated conversion function.
func Convert_softwarecomposition_Document_To_v1beta1_Document(in *softwarecomposition.Document, out *Document, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Document_To_v1beta1_Document(in, out, s)
}

func autoConvert_v1beta1_ExternalDocumentRef_To_softwarecomposition_ExternalDocumentRef(in *ExternalDocumentRef, out *softwarecomposition.ExternalDocumentRef, s conversion.Scope) error {
	out.DocumentRefID = in.DocumentRefID
	out.URI = in.URI
	if err := Convert_v1beta1_Checksum_To_softwarecomposition_Checksum(&in.Checksum, &out.Checksum, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ExternalDocumentRef_To_softwarecomposition_ExternalDocumentRef is an autogenerated conversion function.
func Convert_v1beta1_ExternalDocumentRef_To_softwarecomposition_ExternalDocumentRef(in *ExternalDocumentRef, out *softwarecomposition.ExternalDocumentRef, s conversion.Scope) error {
	return autoConvert_v1beta1_ExternalDocumentRef_To_softwarecomposition_ExternalDocumentRef(in, out, s)
}

func autoConvert_softwarecomposition_ExternalDocumentRef_To_v1beta1_ExternalDocumentRef(in *softwarecomposition.ExternalDocumentRef, out *ExternalDocumentRef, s conversion.Scope) error {
	out.DocumentRefID = in.DocumentRefID
	out.URI = in.URI
	if err := Convert_softwarecomposition_Checksum_To_v1beta1_Checksum(&in.Checksum, &out.Checksum, s); err != nil {
		return err
	}
	return nil
}

// Convert_softwarecomposition_ExternalDocumentRef_To_v1beta1_ExternalDocumentRef is an autogenerated conversion function.
func Convert_softwarecomposition_ExternalDocumentRef_To_v1beta1_ExternalDocumentRef(in *softwarecomposition.ExternalDocumentRef, out *ExternalDocumentRef, s conversion.Scope) error {
	return autoConvert_softwarecomposition_ExternalDocumentRef_To_v1beta1_ExternalDocumentRef(in, out, s)
}

func autoConvert_v1beta1_File_To_softwarecomposition_File(in *File, out *softwarecomposition.File, s conversion.Scope) error {
	out.FileName = in.FileName
	out.FileSPDXIdentifier = softwarecomposition.ElementID(in.FileSPDXIdentifier)
	out.FileTypes = *(*[]string)(unsafe.Pointer(&in.FileTypes))
	out.Checksums = *(*[]softwarecomposition.Checksum)(unsafe.Pointer(&in.Checksums))
	out.LicenseConcluded = in.LicenseConcluded
	out.LicenseInfoInFiles = *(*[]string)(unsafe.Pointer(&in.LicenseInfoInFiles))
	out.LicenseComments = in.LicenseComments
	out.FileCopyrightText = in.FileCopyrightText
	out.ArtifactOfProjects = *(*[]*softwarecomposition.ArtifactOfProject)(unsafe.Pointer(&in.ArtifactOfProjects))
	out.FileComment = in.FileComment
	out.FileNotice = in.FileNotice
	out.FileContributors = *(*[]string)(unsafe.Pointer(&in.FileContributors))
	out.FileAttributionTexts = *(*[]string)(unsafe.Pointer(&in.FileAttributionTexts))
	out.FileDependencies = *(*[]string)(unsafe.Pointer(&in.FileDependencies))
	out.Snippets = *(*map[softwarecomposition.ElementID]*softwarecomposition.Snippet)(unsafe.Pointer(&in.Snippets))
	out.Annotations = *(*[]softwarecomposition.Annotation)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1beta1_File_To_softwarecomposition_File is an autogenerated conversion function.
func Convert_v1beta1_File_To_softwarecomposition_File(in *File, out *softwarecomposition.File, s conversion.Scope) error {
	return autoConvert_v1beta1_File_To_softwarecomposition_File(in, out, s)
}

func autoConvert_softwarecomposition_File_To_v1beta1_File(in *softwarecomposition.File, out *File, s conversion.Scope) error {
	out.FileName = in.FileName
	out.FileSPDXIdentifier = ElementID(in.FileSPDXIdentifier)
	out.FileTypes = *(*[]string)(unsafe.Pointer(&in.FileTypes))
	out.Checksums = *(*[]Checksum)(unsafe.Pointer(&in.Checksums))
	out.LicenseConcluded = in.LicenseConcluded
	out.LicenseInfoInFiles = *(*[]string)(unsafe.Pointer(&in.LicenseInfoInFiles))
	out.LicenseComments = in.LicenseComments
	out.FileCopyrightText = in.FileCopyrightText
	out.ArtifactOfProjects = *(*[]*ArtifactOfProject)(unsafe.Pointer(&in.ArtifactOfProjects))
	out.FileComment = in.FileComment
	out.FileNotice = in.FileNotice
	out.FileContributors = *(*[]string)(unsafe.Pointer(&in.FileContributors))
	out.FileAttributionTexts = *(*[]string)(unsafe.Pointer(&in.FileAttributionTexts))
	out.FileDependencies = *(*[]string)(unsafe.Pointer(&in.FileDependencies))
	out.Snippets = *(*map[ElementID]*Snippet)(unsafe.Pointer(&in.Snippets))
	out.Annotations = *(*[]Annotation)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_softwarecomposition_File_To_v1beta1_File is an autogenerated conversion function.
func Convert_softwarecomposition_File_To_v1beta1_File(in *softwarecomposition.File, out *File, s conversion.Scope) error {
	return autoConvert_softwarecomposition_File_To_v1beta1_File(in, out, s)
}

func autoConvert_v1beta1_Originator_To_softwarecomposition_Originator(in *Originator, out *softwarecomposition.Originator, s conversion.Scope) error {
	out.Originator = in.Originator
	out.OriginatorType = in.OriginatorType
	return nil
}

// Convert_v1beta1_Originator_To_softwarecomposition_Originator is an autogenerated conversion function.
func Convert_v1beta1_Originator_To_softwarecomposition_Originator(in *Originator, out *softwarecomposition.Originator, s conversion.Scope) error {
	return autoConvert_v1beta1_Originator_To_softwarecomposition_Originator(in, out, s)
}

func autoConvert_softwarecomposition_Originator_To_v1beta1_Originator(in *softwarecomposition.Originator, out *Originator, s conversion.Scope) error {
	out.Originator = in.Originator
	out.OriginatorType = in.OriginatorType
	return nil
}

// Convert_softwarecomposition_Originator_To_v1beta1_Originator is an autogenerated conversion function.
func Convert_softwarecomposition_Originator_To_v1beta1_Originator(in *softwarecomposition.Originator, out *Originator, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Originator_To_v1beta1_Originator(in, out, s)
}

func autoConvert_v1beta1_OtherLicense_To_softwarecomposition_OtherLicense(in *OtherLicense, out *softwarecomposition.OtherLicense, s conversion.Scope) error {
	out.LicenseIdentifier = in.LicenseIdentifier
	out.ExtractedText = in.ExtractedText
	out.LicenseName = in.LicenseName
	out.LicenseCrossReferences = *(*[]string)(unsafe.Pointer(&in.LicenseCrossReferences))
	out.LicenseComment = in.LicenseComment
	return nil
}

// Convert_v1beta1_OtherLicense_To_softwarecomposition_OtherLicense is an autogenerated conversion function.
func Convert_v1beta1_OtherLicense_To_softwarecomposition_OtherLicense(in *OtherLicense, out *softwarecomposition.OtherLicense, s conversion.Scope) error {
	return autoConvert_v1beta1_OtherLicense_To_softwarecomposition_OtherLicense(in, out, s)
}

func autoConvert_softwarecomposition_OtherLicense_To_v1beta1_OtherLicense(in *softwarecomposition.OtherLicense, out *OtherLicense, s conversion.Scope) error {
	out.LicenseIdentifier = in.LicenseIdentifier
	out.ExtractedText = in.ExtractedText
	out.LicenseName = in.LicenseName
	out.LicenseCrossReferences = *(*[]string)(unsafe.Pointer(&in.LicenseCrossReferences))
	out.LicenseComment = in.LicenseComment
	return nil
}

// Convert_softwarecomposition_OtherLicense_To_v1beta1_OtherLicense is an autogenerated conversion function.
func Convert_softwarecomposition_OtherLicense_To_v1beta1_OtherLicense(in *softwarecomposition.OtherLicense, out *OtherLicense, s conversion.Scope) error {
	return autoConvert_softwarecomposition_OtherLicense_To_v1beta1_OtherLicense(in, out, s)
}

func autoConvert_v1beta1_Package_To_softwarecomposition_Package(in *Package, out *softwarecomposition.Package, s conversion.Scope) error {
	out.HasFiles = *(*[]string)(unsafe.Pointer(&in.HasFiles))
	out.IsUnpackaged = in.IsUnpackaged
	out.PackageName = in.PackageName
	out.PackageSPDXIdentifier = softwarecomposition.ElementID(in.PackageSPDXIdentifier)
	out.PackageVersion = in.PackageVersion
	out.PackageFileName = in.PackageFileName
	out.PackageSupplier = (*softwarecomposition.Supplier)(unsafe.Pointer(in.PackageSupplier))
	out.PackageOriginator = (*softwarecomposition.Originator)(unsafe.Pointer(in.PackageOriginator))
	out.PackageDownloadLocation = in.PackageDownloadLocation
	out.FilesAnalyzed = in.FilesAnalyzed
	out.IsFilesAnalyzedTagPresent = in.IsFilesAnalyzedTagPresent
	out.PackageVerificationCode = (*softwarecomposition.PackageVerificationCode)(unsafe.Pointer(in.PackageVerificationCode))
	out.PackageChecksums = *(*[]softwarecomposition.Checksum)(unsafe.Pointer(&in.PackageChecksums))
	out.PackageHomePage = in.PackageHomePage
	out.PackageSourceInfo = in.PackageSourceInfo
	out.PackageLicenseConcluded = in.PackageLicenseConcluded
	out.PackageLicenseInfoFromFiles = *(*[]string)(unsafe.Pointer(&in.PackageLicenseInfoFromFiles))
	out.PackageLicenseDeclared = in.PackageLicenseDeclared
	out.PackageLicenseComments = in.PackageLicenseComments
	out.PackageCopyrightText = in.PackageCopyrightText
	out.PackageSummary = in.PackageSummary
	out.PackageDescription = in.PackageDescription
	out.PackageComment = in.PackageComment
	out.PackageExternalReferences = *(*[]*softwarecomposition.PackageExternalReference)(unsafe.Pointer(&in.PackageExternalReferences))
	out.PackageAttributionTexts = *(*[]string)(unsafe.Pointer(&in.PackageAttributionTexts))
	out.PrimaryPackagePurpose = in.PrimaryPackagePurpose
	out.ReleaseDate = in.ReleaseDate
	out.BuiltDate = in.BuiltDate
	out.ValidUntilDate = in.ValidUntilDate
	out.Files = *(*[]*softwarecomposition.File)(unsafe.Pointer(&in.Files))
	out.Annotations = *(*[]softwarecomposition.Annotation)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1beta1_Package_To_softwarecomposition_Package is an autogenerated conversion function.
func Convert_v1beta1_Package_To_softwarecomposition_Package(in *Package, out *softwarecomposition.Package, s conversion.Scope) error {
	return autoConvert_v1beta1_Package_To_softwarecomposition_Package(in, out, s)
}

func autoConvert_softwarecomposition_Package_To_v1beta1_Package(in *softwarecomposition.Package, out *Package, s conversion.Scope) error {
	out.HasFiles = *(*[]string)(unsafe.Pointer(&in.HasFiles))
	out.IsUnpackaged = in.IsUnpackaged
	out.PackageName = in.PackageName
	out.PackageSPDXIdentifier = ElementID(in.PackageSPDXIdentifier)
	out.PackageVersion = in.PackageVersion
	out.PackageFileName = in.PackageFileName
	out.PackageSupplier = (*Supplier)(unsafe.Pointer(in.PackageSupplier))
	out.PackageOriginator = (*Originator)(unsafe.Pointer(in.PackageOriginator))
	out.PackageDownloadLocation = in.PackageDownloadLocation
	out.FilesAnalyzed = in.FilesAnalyzed
	out.IsFilesAnalyzedTagPresent = in.IsFilesAnalyzedTagPresent
	out.PackageVerificationCode = (*PackageVerificationCode)(unsafe.Pointer(in.PackageVerificationCode))
	out.PackageChecksums = *(*[]Checksum)(unsafe.Pointer(&in.PackageChecksums))
	out.PackageHomePage = in.PackageHomePage
	out.PackageSourceInfo = in.PackageSourceInfo
	out.PackageLicenseConcluded = in.PackageLicenseConcluded
	out.PackageLicenseInfoFromFiles = *(*[]string)(unsafe.Pointer(&in.PackageLicenseInfoFromFiles))
	out.PackageLicenseDeclared = in.PackageLicenseDeclared
	out.PackageLicenseComments = in.PackageLicenseComments
	out.PackageCopyrightText = in.PackageCopyrightText
	out.PackageSummary = in.PackageSummary
	out.PackageDescription = in.PackageDescription
	out.PackageComment = in.PackageComment
	out.PackageExternalReferences = *(*[]*PackageExternalReference)(unsafe.Pointer(&in.PackageExternalReferences))
	out.PackageAttributionTexts = *(*[]string)(unsafe.Pointer(&in.PackageAttributionTexts))
	out.PrimaryPackagePurpose = in.PrimaryPackagePurpose
	out.ReleaseDate = in.ReleaseDate
	out.BuiltDate = in.BuiltDate
	out.ValidUntilDate = in.ValidUntilDate
	out.Files = *(*[]*File)(unsafe.Pointer(&in.Files))
	out.Annotations = *(*[]Annotation)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_softwarecomposition_Package_To_v1beta1_Package is an autogenerated conversion function.
func Convert_softwarecomposition_Package_To_v1beta1_Package(in *softwarecomposition.Package, out *Package, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Package_To_v1beta1_Package(in, out, s)
}

func autoConvert_v1beta1_PackageExternalReference_To_softwarecomposition_PackageExternalReference(in *PackageExternalReference, out *softwarecomposition.PackageExternalReference, s conversion.Scope) error {
	out.Category = in.Category
	out.RefType = in.RefType
	out.Locator = in.Locator
	out.ExternalRefComment = in.ExternalRefComment
	return nil
}

// Convert_v1beta1_PackageExternalReference_To_softwarecomposition_PackageExternalReference is an autogenerated conversion function.
func Convert_v1beta1_PackageExternalReference_To_softwarecomposition_PackageExternalReference(in *PackageExternalReference, out *softwarecomposition.PackageExternalReference, s conversion.Scope) error {
	return autoConvert_v1beta1_PackageExternalReference_To_softwarecomposition_PackageExternalReference(in, out, s)
}

func autoConvert_softwarecomposition_PackageExternalReference_To_v1beta1_PackageExternalReference(in *softwarecomposition.PackageExternalReference, out *PackageExternalReference, s conversion.Scope) error {
	out.Category = in.Category
	out.RefType = in.RefType
	out.Locator = in.Locator
	out.ExternalRefComment = in.ExternalRefComment
	return nil
}

// Convert_softwarecomposition_PackageExternalReference_To_v1beta1_PackageExternalReference is an autogenerated conversion function.
func Convert_softwarecomposition_PackageExternalReference_To_v1beta1_PackageExternalReference(in *softwarecomposition.PackageExternalReference, out *PackageExternalReference, s conversion.Scope) error {
	return autoConvert_softwarecomposition_PackageExternalReference_To_v1beta1_PackageExternalReference(in, out, s)
}

func autoConvert_v1beta1_PackageVerificationCode_To_softwarecomposition_PackageVerificationCode(in *PackageVerificationCode, out *softwarecomposition.PackageVerificationCode, s conversion.Scope) error {
	out.Value = in.Value
	out.ExcludedFiles = *(*[]string)(unsafe.Pointer(&in.ExcludedFiles))
	return nil
}

// Convert_v1beta1_PackageVerificationCode_To_softwarecomposition_PackageVerificationCode is an autogenerated conversion function.
func Convert_v1beta1_PackageVerificationCode_To_softwarecomposition_PackageVerificationCode(in *PackageVerificationCode, out *softwarecomposition.PackageVerificationCode, s conversion.Scope) error {
	return autoConvert_v1beta1_PackageVerificationCode_To_softwarecomposition_PackageVerificationCode(in, out, s)
}

func autoConvert_softwarecomposition_PackageVerificationCode_To_v1beta1_PackageVerificationCode(in *softwarecomposition.PackageVerificationCode, out *PackageVerificationCode, s conversion.Scope) error {
	out.Value = in.Value
	out.ExcludedFiles = *(*[]string)(unsafe.Pointer(&in.ExcludedFiles))
	return nil
}

// Convert_softwarecomposition_PackageVerificationCode_To_v1beta1_PackageVerificationCode is an autogenerated conversion function.
func Convert_softwarecomposition_PackageVerificationCode_To_v1beta1_PackageVerificationCode(in *softwarecomposition.PackageVerificationCode, out *PackageVerificationCode, s conversion.Scope) error {
	return autoConvert_softwarecomposition_PackageVerificationCode_To_v1beta1_PackageVerificationCode(in, out, s)
}

func autoConvert_v1beta1_Relationship_To_softwarecomposition_Relationship(in *Relationship, out *softwarecomposition.Relationship, s conversion.Scope) error {
	if err := Convert_v1beta1_DocElementID_To_softwarecomposition_DocElementID(&in.RefA, &out.RefA, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DocElementID_To_softwarecomposition_DocElementID(&in.RefB, &out.RefB, s); err != nil {
		return err
	}
	out.Relationship = in.Relationship
	out.RelationshipComment = in.RelationshipComment
	return nil
}

// Convert_v1beta1_Relationship_To_softwarecomposition_Relationship is an autogenerated conversion function.
func Convert_v1beta1_Relationship_To_softwarecomposition_Relationship(in *Relationship, out *softwarecomposition.Relationship, s conversion.Scope) error {
	return autoConvert_v1beta1_Relationship_To_softwarecomposition_Relationship(in, out, s)
}

func autoConvert_softwarecomposition_Relationship_To_v1beta1_Relationship(in *softwarecomposition.Relationship, out *Relationship, s conversion.Scope) error {
	if err := Convert_softwarecomposition_DocElementID_To_v1beta1_DocElementID(&in.RefA, &out.RefA, s); err != nil {
		return err
	}
	if err := Convert_softwarecomposition_DocElementID_To_v1beta1_DocElementID(&in.RefB, &out.RefB, s); err != nil {
		return err
	}
	out.Relationship = in.Relationship
	out.RelationshipComment = in.RelationshipComment
	return nil
}

// Convert_softwarecomposition_Relationship_To_v1beta1_Relationship is an autogenerated conversion function.
func Convert_softwarecomposition_Relationship_To_v1beta1_Relationship(in *softwarecomposition.Relationship, out *Relationship, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Relationship_To_v1beta1_Relationship(in, out, s)
}

func autoConvert_v1beta1_Review_To_softwarecomposition_Review(in *Review, out *softwarecomposition.Review, s conversion.Scope) error {
	out.Reviewer = in.Reviewer
	out.ReviewerType = in.ReviewerType
	out.ReviewDate = in.ReviewDate
	out.ReviewComment = in.ReviewComment
	return nil
}

// Convert_v1beta1_Review_To_softwarecomposition_Review is an autogenerated conversion function.
func Convert_v1beta1_Review_To_softwarecomposition_Review(in *Review, out *softwarecomposition.Review, s conversion.Scope) error {
	return autoConvert_v1beta1_Review_To_softwarecomposition_Review(in, out, s)
}

func autoConvert_softwarecomposition_Review_To_v1beta1_Review(in *softwarecomposition.Review, out *Review, s conversion.Scope) error {
	out.Reviewer = in.Reviewer
	out.ReviewerType = in.ReviewerType
	out.ReviewDate = in.ReviewDate
	out.ReviewComment = in.ReviewComment
	return nil
}

// Convert_softwarecomposition_Review_To_v1beta1_Review is an autogenerated conversion function.
func Convert_softwarecomposition_Review_To_v1beta1_Review(in *softwarecomposition.Review, out *Review, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Review_To_v1beta1_Review(in, out, s)
}

func autoConvert_v1beta1_SBOMSPDXv2p3_To_softwarecomposition_SBOMSPDXv2p3(in *SBOMSPDXv2p3, out *softwarecomposition.SBOMSPDXv2p3, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SBOMSPDXv2p3Spec_To_softwarecomposition_SBOMSPDXv2p3Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SBOMSPDXv2p3Status_To_softwarecomposition_SBOMSPDXv2p3Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SBOMSPDXv2p3_To_softwarecomposition_SBOMSPDXv2p3 is an autogenerated conversion function.
func Convert_v1beta1_SBOMSPDXv2p3_To_softwarecomposition_SBOMSPDXv2p3(in *SBOMSPDXv2p3, out *softwarecomposition.SBOMSPDXv2p3, s conversion.Scope) error {
	return autoConvert_v1beta1_SBOMSPDXv2p3_To_softwarecomposition_SBOMSPDXv2p3(in, out, s)
}

func autoConvert_softwarecomposition_SBOMSPDXv2p3_To_v1beta1_SBOMSPDXv2p3(in *softwarecomposition.SBOMSPDXv2p3, out *SBOMSPDXv2p3, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_softwarecomposition_SBOMSPDXv2p3Spec_To_v1beta1_SBOMSPDXv2p3Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_softwarecomposition_SBOMSPDXv2p3Status_To_v1beta1_SBOMSPDXv2p3Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_softwarecomposition_SBOMSPDXv2p3_To_v1beta1_SBOMSPDXv2p3 is an autogenerated conversion function.
func Convert_softwarecomposition_SBOMSPDXv2p3_To_v1beta1_SBOMSPDXv2p3(in *softwarecomposition.SBOMSPDXv2p3, out *SBOMSPDXv2p3, s conversion.Scope) error {
	return autoConvert_softwarecomposition_SBOMSPDXv2p3_To_v1beta1_SBOMSPDXv2p3(in, out, s)
}

func autoConvert_v1beta1_SBOMSPDXv2p3List_To_softwarecomposition_SBOMSPDXv2p3List(in *SBOMSPDXv2p3List, out *softwarecomposition.SBOMSPDXv2p3List, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]softwarecomposition.SBOMSPDXv2p3)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_SBOMSPDXv2p3List_To_softwarecomposition_SBOMSPDXv2p3List is an autogenerated conversion function.
func Convert_v1beta1_SBOMSPDXv2p3List_To_softwarecomposition_SBOMSPDXv2p3List(in *SBOMSPDXv2p3List, out *softwarecomposition.SBOMSPDXv2p3List, s conversion.Scope) error {
	return autoConvert_v1beta1_SBOMSPDXv2p3List_To_softwarecomposition_SBOMSPDXv2p3List(in, out, s)
}

func autoConvert_softwarecomposition_SBOMSPDXv2p3List_To_v1beta1_SBOMSPDXv2p3List(in *softwarecomposition.SBOMSPDXv2p3List, out *SBOMSPDXv2p3List, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SBOMSPDXv2p3)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_softwarecomposition_SBOMSPDXv2p3List_To_v1beta1_SBOMSPDXv2p3List is an autogenerated conversion function.
func Convert_softwarecomposition_SBOMSPDXv2p3List_To_v1beta1_SBOMSPDXv2p3List(in *softwarecomposition.SBOMSPDXv2p3List, out *SBOMSPDXv2p3List, s conversion.Scope) error {
	return autoConvert_softwarecomposition_SBOMSPDXv2p3List_To_v1beta1_SBOMSPDXv2p3List(in, out, s)
}

func autoConvert_v1beta1_SBOMSPDXv2p3Spec_To_softwarecomposition_SBOMSPDXv2p3Spec(in *SBOMSPDXv2p3Spec, out *softwarecomposition.SBOMSPDXv2p3Spec, s conversion.Scope) error {
	if err := Convert_v1beta1_Document_To_softwarecomposition_Document(&in.SPDX, &out.SPDX, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SBOMSPDXv2p3Spec_To_softwarecomposition_SBOMSPDXv2p3Spec is an autogenerated conversion function.
func Convert_v1beta1_SBOMSPDXv2p3Spec_To_softwarecomposition_SBOMSPDXv2p3Spec(in *SBOMSPDXv2p3Spec, out *softwarecomposition.SBOMSPDXv2p3Spec, s conversion.Scope) error {
	return autoConvert_v1beta1_SBOMSPDXv2p3Spec_To_softwarecomposition_SBOMSPDXv2p3Spec(in, out, s)
}

func autoConvert_softwarecomposition_SBOMSPDXv2p3Spec_To_v1beta1_SBOMSPDXv2p3Spec(in *softwarecomposition.SBOMSPDXv2p3Spec, out *SBOMSPDXv2p3Spec, s conversion.Scope) error {
	if err := Convert_softwarecomposition_Document_To_v1beta1_Document(&in.SPDX, &out.SPDX, s); err != nil {
		return err
	}
	return nil
}

// Convert_softwarecomposition_SBOMSPDXv2p3Spec_To_v1beta1_SBOMSPDXv2p3Spec is an autogenerated conversion function.
func Convert_softwarecomposition_SBOMSPDXv2p3Spec_To_v1beta1_SBOMSPDXv2p3Spec(in *softwarecomposition.SBOMSPDXv2p3Spec, out *SBOMSPDXv2p3Spec, s conversion.Scope) error {
	return autoConvert_softwarecomposition_SBOMSPDXv2p3Spec_To_v1beta1_SBOMSPDXv2p3Spec(in, out, s)
}

func autoConvert_v1beta1_SBOMSPDXv2p3Status_To_softwarecomposition_SBOMSPDXv2p3Status(in *SBOMSPDXv2p3Status, out *softwarecomposition.SBOMSPDXv2p3Status, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_SBOMSPDXv2p3Status_To_softwarecomposition_SBOMSPDXv2p3Status is an autogenerated conversion function.
func Convert_v1beta1_SBOMSPDXv2p3Status_To_softwarecomposition_SBOMSPDXv2p3Status(in *SBOMSPDXv2p3Status, out *softwarecomposition.SBOMSPDXv2p3Status, s conversion.Scope) error {
	return autoConvert_v1beta1_SBOMSPDXv2p3Status_To_softwarecomposition_SBOMSPDXv2p3Status(in, out, s)
}

func autoConvert_softwarecomposition_SBOMSPDXv2p3Status_To_v1beta1_SBOMSPDXv2p3Status(in *softwarecomposition.SBOMSPDXv2p3Status, out *SBOMSPDXv2p3Status, s conversion.Scope) error {
	return nil
}

// Convert_softwarecomposition_SBOMSPDXv2p3Status_To_v1beta1_SBOMSPDXv2p3Status is an autogenerated conversion function.
func Convert_softwarecomposition_SBOMSPDXv2p3Status_To_v1beta1_SBOMSPDXv2p3Status(in *softwarecomposition.SBOMSPDXv2p3Status, out *SBOMSPDXv2p3Status, s conversion.Scope) error {
	return autoConvert_softwarecomposition_SBOMSPDXv2p3Status_To_v1beta1_SBOMSPDXv2p3Status(in, out, s)
}

func autoConvert_v1beta1_Snippet_To_softwarecomposition_Snippet(in *Snippet, out *softwarecomposition.Snippet, s conversion.Scope) error {
	out.SnippetSPDXIdentifier = softwarecomposition.ElementID(in.SnippetSPDXIdentifier)
	out.SnippetFromFileSPDXIdentifier = softwarecomposition.ElementID(in.SnippetFromFileSPDXIdentifier)
	out.Ranges = *(*[]softwarecomposition.SnippetRange)(unsafe.Pointer(&in.Ranges))
	out.SnippetLicenseConcluded = in.SnippetLicenseConcluded
	out.LicenseInfoInSnippet = *(*[]string)(unsafe.Pointer(&in.LicenseInfoInSnippet))
	out.SnippetLicenseComments = in.SnippetLicenseComments
	out.SnippetCopyrightText = in.SnippetCopyrightText
	out.SnippetComment = in.SnippetComment
	out.SnippetName = in.SnippetName
	out.SnippetAttributionTexts = *(*[]string)(unsafe.Pointer(&in.SnippetAttributionTexts))
	return nil
}

// Convert_v1beta1_Snippet_To_softwarecomposition_Snippet is an autogenerated conversion function.
func Convert_v1beta1_Snippet_To_softwarecomposition_Snippet(in *Snippet, out *softwarecomposition.Snippet, s conversion.Scope) error {
	return autoConvert_v1beta1_Snippet_To_softwarecomposition_Snippet(in, out, s)
}

func autoConvert_softwarecomposition_Snippet_To_v1beta1_Snippet(in *softwarecomposition.Snippet, out *Snippet, s conversion.Scope) error {
	out.SnippetSPDXIdentifier = ElementID(in.SnippetSPDXIdentifier)
	out.SnippetFromFileSPDXIdentifier = ElementID(in.SnippetFromFileSPDXIdentifier)
	out.Ranges = *(*[]SnippetRange)(unsafe.Pointer(&in.Ranges))
	out.SnippetLicenseConcluded = in.SnippetLicenseConcluded
	out.LicenseInfoInSnippet = *(*[]string)(unsafe.Pointer(&in.LicenseInfoInSnippet))
	out.SnippetLicenseComments = in.SnippetLicenseComments
	out.SnippetCopyrightText = in.SnippetCopyrightText
	out.SnippetComment = in.SnippetComment
	out.SnippetName = in.SnippetName
	out.SnippetAttributionTexts = *(*[]string)(unsafe.Pointer(&in.SnippetAttributionTexts))
	return nil
}

// Convert_softwarecomposition_Snippet_To_v1beta1_Snippet is an autogenerated conversion function.
func Convert_softwarecomposition_Snippet_To_v1beta1_Snippet(in *softwarecomposition.Snippet, out *Snippet, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Snippet_To_v1beta1_Snippet(in, out, s)
}

func autoConvert_v1beta1_SnippetRange_To_softwarecomposition_SnippetRange(in *SnippetRange, out *softwarecomposition.SnippetRange, s conversion.Scope) error {
	if err := Convert_v1beta1_SnippetRangePointer_To_softwarecomposition_SnippetRangePointer(&in.StartPointer, &out.StartPointer, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SnippetRangePointer_To_softwarecomposition_SnippetRangePointer(&in.EndPointer, &out.EndPointer, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SnippetRange_To_softwarecomposition_SnippetRange is an autogenerated conversion function.
func Convert_v1beta1_SnippetRange_To_softwarecomposition_SnippetRange(in *SnippetRange, out *softwarecomposition.SnippetRange, s conversion.Scope) error {
	return autoConvert_v1beta1_SnippetRange_To_softwarecomposition_SnippetRange(in, out, s)
}

func autoConvert_softwarecomposition_SnippetRange_To_v1beta1_SnippetRange(in *softwarecomposition.SnippetRange, out *SnippetRange, s conversion.Scope) error {
	if err := Convert_softwarecomposition_SnippetRangePointer_To_v1beta1_SnippetRangePointer(&in.StartPointer, &out.StartPointer, s); err != nil {
		return err
	}
	if err := Convert_softwarecomposition_SnippetRangePointer_To_v1beta1_SnippetRangePointer(&in.EndPointer, &out.EndPointer, s); err != nil {
		return err
	}
	return nil
}

// Convert_softwarecomposition_SnippetRange_To_v1beta1_SnippetRange is an autogenerated conversion function.
func Convert_softwarecomposition_SnippetRange_To_v1beta1_SnippetRange(in *softwarecomposition.SnippetRange, out *SnippetRange, s conversion.Scope) error {
	return autoConvert_softwarecomposition_SnippetRange_To_v1beta1_SnippetRange(in, out, s)
}

func autoConvert_v1beta1_SnippetRangePointer_To_softwarecomposition_SnippetRangePointer(in *SnippetRangePointer, out *softwarecomposition.SnippetRangePointer, s conversion.Scope) error {
	out.Offset = in.Offset
	out.LineNumber = in.LineNumber
	out.FileSPDXIdentifier = softwarecomposition.ElementID(in.FileSPDXIdentifier)
	return nil
}

// Convert_v1beta1_SnippetRangePointer_To_softwarecomposition_SnippetRangePointer is an autogenerated conversion function.
func Convert_v1beta1_SnippetRangePointer_To_softwarecomposition_SnippetRangePointer(in *SnippetRangePointer, out *softwarecomposition.SnippetRangePointer, s conversion.Scope) error {
	return autoConvert_v1beta1_SnippetRangePointer_To_softwarecomposition_SnippetRangePointer(in, out, s)
}

func autoConvert_softwarecomposition_SnippetRangePointer_To_v1beta1_SnippetRangePointer(in *softwarecomposition.SnippetRangePointer, out *SnippetRangePointer, s conversion.Scope) error {
	out.Offset = in.Offset
	out.LineNumber = in.LineNumber
	out.FileSPDXIdentifier = ElementID(in.FileSPDXIdentifier)
	return nil
}

// Convert_softwarecomposition_SnippetRangePointer_To_v1beta1_SnippetRangePointer is an autogenerated conversion function.
func Convert_softwarecomposition_SnippetRangePointer_To_v1beta1_SnippetRangePointer(in *softwarecomposition.SnippetRangePointer, out *SnippetRangePointer, s conversion.Scope) error {
	return autoConvert_softwarecomposition_SnippetRangePointer_To_v1beta1_SnippetRangePointer(in, out, s)
}

func autoConvert_v1beta1_Supplier_To_softwarecomposition_Supplier(in *Supplier, out *softwarecomposition.Supplier, s conversion.Scope) error {
	out.Supplier = in.Supplier
	out.SupplierType = in.SupplierType
	return nil
}

// Convert_v1beta1_Supplier_To_softwarecomposition_Supplier is an autogenerated conversion function.
func Convert_v1beta1_Supplier_To_softwarecomposition_Supplier(in *Supplier, out *softwarecomposition.Supplier, s conversion.Scope) error {
	return autoConvert_v1beta1_Supplier_To_softwarecomposition_Supplier(in, out, s)
}

func autoConvert_softwarecomposition_Supplier_To_v1beta1_Supplier(in *softwarecomposition.Supplier, out *Supplier, s conversion.Scope) error {
	out.Supplier = in.Supplier
	out.SupplierType = in.SupplierType
	return nil
}

// Convert_softwarecomposition_Supplier_To_v1beta1_Supplier is an autogenerated conversion function.
func Convert_softwarecomposition_Supplier_To_v1beta1_Supplier(in *softwarecomposition.Supplier, out *Supplier, s conversion.Scope) error {
	return autoConvert_softwarecomposition_Supplier_To_v1beta1_Supplier(in, out, s)
}
