apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardle-server
  namespace: wardle
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: wardle-server
        image: vklokun/kube-sample-apiserver:0.1.21
        imagePullPolicy: Always
        args: [ "--etcd-servers=http://localhost:2379" ]
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.7
