apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardle-server
  namespace: wardle
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: wardle-server
        image: vklokun/kube-sample-apiserver:0.1.38
        imagePullPolicy: Always
        args: [ "--etcd-servers=http://kubescape-aa-storage-etcd:2379" ]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubescape-aa-storage-etcd
  namespace: wardle
  labels:
    app.kubernetes.io/name: "etcd"
    app.kubernetes.io/component: "database"
    app.kubernetes.io/part-of: "kubescape-aa-storage"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "etcd"
      app.kubernetes.io/component: "database"
      app.kubernetes.io/part-of: "kubescape-aa-storage"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "etcd"
        app.kubernetes.io/component: "database"
        app.kubernetes.io/part-of: "kubescape-aa-storage"
    spec:
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.7
        args:
          - "etcd"
          - "--listen-client-urls=http://0.0.0.0:2379"
          - "--advertise-client-urls=http://0.0.0.0:2379"
          - "--max-request-bytes=25165824"
        ports:
          - name: "etcd-port"
            protocol: "TCP"
            containerPort: 2379
---

apiVersion: v1
kind: Service
metadata:
  name: "kubescape-aa-storage-etcd"
  namespace: "wardle"
  labels:
    app.kubernetes.io/name: "etcd"
    app.kubernetes.io/component: "database"
    app.kubernetes.io/part-of: "kubescape-aa-storage"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "etcd"
    app.kubernetes.io/component: "database"
    app.kubernetes.io/part-of: "kubescape-aa-storage"
  ports:
  - name: "etcd-port"
    protocol: "TCP"
    port: 2379
    targetPort: "etcd-port"
