name: pull_request_created
permissions: read-all

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '*.md'
      - '*.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-created:
    permissions:
      contents: read
      actions: read
      pull-requests: write
      security-events: write
    uses: kubescape/workflows/.github/workflows/incluster-comp-pr-created.yaml@33aa46c0214e9e1455e0fc069abc1a9dcdfceb0b # configurable test timeout
    with:
      CGO_ENABLED: 0
      GO_VERSION: "1.25"
      TEST_TIMEOUT_MINUTES: 30
    secrets: inherit
